server:
  port: 8884
spring:
  application:
    name: NOTIFICATION-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8065/eureka/