server:
  port: 8882
spring:
  application:
    name: COMMUNICATION-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8065/eureka/