server:
  port: 8883
spring:
  application:
    name: EVENT-MANAGEMENT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8065/eureka/